version: '3.13.0'

services:
  web:
    build:
      context: .
    command: ./start.sh
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
